# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('promedio', models.FloatField()),
                ('detalle', models.CharField(max_length=200)),
                ('modulo_estudiante', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('documento', models.IntegerField()),
                ('Foto', models.ImageField(null=True, upload_to='/media')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('jornada', models.CharField(max_length=120)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Curso')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('indice', models.IntegerField(null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cel', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='/media')),
                ('profesion', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profe',
                'verbose_name_plural': 'Profes',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('indice', models.IntegerField(null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Preguntas')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Profesor'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='grupo_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Grupo_Estudiante'),
        ),
    ]
