# Generated by Django 2.2.4 on 2021-09-15 23:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.BigIntegerField(null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('documento', models.BigIntegerField()),
                ('Foto', models.ImageField(null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('jornada', models.CharField(max_length=120)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('tiempo', models.DateTimeField(default=datetime.datetime.now)),
                ('accion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('indice', models.IntegerField(null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cel', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.BigIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media')),
                ('profesion', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profe',
                'verbose_name_plural': 'Profes',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('indice', models.IntegerField(null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Curso')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Profesor'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('promedio', models.FloatField(null=True)),
                ('detalle', models.CharField(max_length=200, null=True)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Actividades')),
                ('grupo_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Grupo_Estudiante')),
            ],
        ),
    ]
