# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('modulo_estudiante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.FloatField()),
                ('fecha_fin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('documento', models.IntegerField()),
                ('Foto', models.ImageField(upload_to='/tmp')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha', models.FloatField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cel', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(db_column='Fecha Nacimiento')),
                ('cedula', models.IntegerField()),
                ('foto', models.ImageField(upload_to='/tmp')),
                ('profesion', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Profe',
                'verbose_name_plural': 'Profes',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Profesor'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Estudiante'),
        ),
    ]
