# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20161116_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Foto',
            field=models.ImageField(null=True, upload_to='/tmp'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
