# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170125_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('tiempo', models.DateTimeField(default=datetime.datetime.now)),
                ('accion', models.TextField()),
            ],
        ),
    ]
