# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='modulo_estudiante',
        ),
    ]
