# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_calificacion_modulo_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Actividades'),
        ),
    ]
