# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_respuesta_indice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
