# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170216_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='promedio',
            field=models.FloatField(null=True),
        ),
    ]
