# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170216_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='detalle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
