# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170216_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.IntegerField(verbose_name=9999999999L),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tel',
            field=models.IntegerField(null=True, verbose_name=9999999999L),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula',
            field=models.IntegerField(verbose_name=9999999999L),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cel',
            field=models.IntegerField(verbose_name=9999999999L),
        ),
    ]
