# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170223_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.BigIntegerField(),
        ),
    ]
