# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_actividades_preguntas_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='indice',
            field=models.IntegerField(null=True),
        ),
    ]
